# Generated by Django 5.1.7 on 2025-05-05 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic_post',
            fields=[
                ('Pic_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pic_name', models.CharField(max_length=100)),
                ('Pic_status', models.CharField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'InOrder')], default='Published', max_length=11)),
                ('Pic_site_publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-Pic_site_publish',),
            },
        ),
    ]
