# Generated by Django 5.1.7 on 2025-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic_post',
            name='Pic_author',
            field=models.CharField(default='Noname', max_length=50),
        ),
        migrations.AddField(
            model_name='pic_post',
            name='Pic_contain',
            field=models.CharField(default='Нет описания', max_length=200),
        ),
        migrations.AddField(
            model_name='pic_post',
            name='Piс_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pic_post',
            name='Pic_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inorder', 'InOrder')], default='Published', max_length=11),
        ),
    ]
