# Generated by Django 5.1.7 on 2025-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_pic_post_pic_author_pic_post_pic_contain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic_post',
            name='Piс_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
