# Generated by Django 5.1.7 on 2025-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_pic_post_piс_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Художник')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Художники',
            },
        ),
        migrations.AddField(
            model_name='pic_post',
            name='Pic_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pic_post',
            name='Pic_slug',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
