# Generated by Django 5.1.7 on 2025-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_pic_post_pic_author_pic_post_pic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic_post',
            name='Pic_slug',
            field=models.SlugField(unique=True),
        ),
    ]
