# Generated by Django 5.1.7 on 2025-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_pic_post_pic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic_post',
            name='Pic_contain',
            field=models.TextField(default='Нет описания', max_length=200),
        ),
    ]
