# Generated by Django 5.1.7 on 2025-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_pic_post_pic_contain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic_post',
            name='Pic_author',
            field=models.ManyToManyField(related_name='artist_name', to='gallery.artists', verbose_name='Artist_name'),
        ),
    ]
