# Generated by Django 5.1.7 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_pic_post_pic_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='pic_post',
            options={'ordering': ('-Pic_site_publish',), 'verbose_name': 'Pictures'},
        ),
        migrations.AddField(
            model_name='pic_post',
            name='Pic_discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
