# Generated by Django 5.1.7 on 2025-05-08 11:55

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_artists_options_alter_pic_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic_post',
            name='Pic_image',
            field=models.ImageField(default='gallery/pics/default.jpg', upload_to=gallery.models.upload_to, verbose_name='Image'),
        ),
    ]
