# Generated by Django 5.1.7 on 2025-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_sold_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic_post',
            name='How_many',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
