# Generated by Django 5.1.7 on 2025-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_pic_post_how_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_pics',
            name='id',
        ),
        migrations.AddField(
            model_name='sold_pics',
            name='Sold_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
