# Generated by Django 5.1.7 on 2025-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_remove_sold_pics_id_sold_pics_sold_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_pics',
            name='Sold_pic',
        ),
        migrations.AddField(
            model_name='sold_pics',
            name='Sold_pic',
            field=models.ManyToManyField(related_name='sold_pic', to='gallery.pic_post', verbose_name='Sold_pic'),
        ),
    ]
