# Generated by Django 5.1.7 on 2025-05-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_remove_sold_pics_sold_pic_sold_pics_sold_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_pics',
            name='Sold_pic',
        ),
        migrations.AddField(
            model_name='sold_pics',
            name='Sold_pic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_pic', to='gallery.pic_post', verbose_name='Sold_pic'),
        ),
    ]
