# Generated by Django 5.1.7 on 2025-05-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_remove_sold_pics_sold_pic_sold_pics_sold_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold_pics',
            name='How_many_sold',
        ),
    ]
