# Generated by Django 5.1.7 on 2025-05-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_sold_pics_how_many_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_pics',
            name='Sold_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_pic', to='gallery.pic_post', verbose_name='Sold_pic'),
        ),
    ]
