# Generated by Django 5.1.7 on 2025-05-08 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_sold_pics_sold_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_pics',
            name='Sold_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
