# Generated by Django 4.2.21 on 2025-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_sold_pics_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_pics',
            name='Sold_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
