# Generated by Django 4.2.21 on 2025-05-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Genres'},
        ),
    ]
