# Generated by Django 4.2.21 on 2025-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_alter_genres_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic_post',
            name='Pic_genre',
            field=models.ManyToManyField(related_name='pic_genre', to='gallery.genres', verbose_name='Pic_genre'),
        ),
    ]
